name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and Push the Docker image
      run: |
        TIMESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag ajayverse/learn-go:$TIMESTAMP
        docker push ajayverse/learn-go:$TIMESTAMP
