name: CI/CD Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Linter
        run: |
          go vet ./...
          go generate ./...
          git diff --exit-code
          go fmt ./...
          git diff --exit-code

  build:
    name: Build Code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          go build -v ./...

  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          go test -v ./... -cover

  docker-push:
    name: Bake and Push Docker Image
    runs-on: ubuntu-22.04
    needs:
      - lint
      - build
      - test
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push the Docker image
        run: |
          TIMESTAMP=$(date +%s)
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/learn-go:$TIMESTAMP
          docker push ${{ secrets.DOCKER_USERNAME }}/learn-go:$TIMESTAMP